# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "codeberg"
name = "Codeberg"
url = "https://github.com/CaiJimmy/hugo-theme-stack"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://twitter.com"

[social.params]
icon = "brand-mastodon"
