# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "Github"
url = "https://github.com/harperbolic"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.gamedev.place/@harper"

[social.params]
icon = "brand-mastodon"
